main: com.cavetale.pocketmob.PocketMobPlugin
name: PocketMob
version: 0.1
api-version: 1.17
description: Capture mob in spawn eggs.
author: StarTux
website: https://cavetale.com

depend: [WorldMarker, Mytems, Core]
softdepend: [Dirty]

commands:
  pocketmob:
    aliases: []
    description: PocketMob Admin Command
    permission: pocketmob.admin
    usage: |-
      /pocketmob

permissions:
  pocketmob.admin:
    description: Use /pocketmob
    default: op
  pocketmob.catch:
    description: Throw MobCatchers and catch PocketMobs
    default: op
